### ISSUE TITLE
Read XLS files (rows number limited to 65535)

### ISSUE THREAD

**Issue by olivierfaure** [miyako/4d-plugin-xls-basic-excel#1]
Hi

Is it a limitation of the library or of the plugin ?

Total rows is max to 65535 and XLS Get ... too.

Thx

Olivier

(in the readme, title is "4d-pugin-xls-basic-excel" (it left a L in plugin) :)

**Comment by olivierfaure** [comment]
Sorry, it's the xlsx to xls conversion that limit the rows numbers in Excel... is it possible to import larger files with more rows with the plugin ?

**Comment by olivierfaure** [comment]
To go further, is there a way to import in 4D .xlsx files ? :)

**Comment by miyako** [comment]
Hello, you can use https://github.com/miyako/4d-plugin-opc to read and write xlsx files but you need some understanding of xlsx

**Comment by olivierfaure** [comment]
Thanks :)
