### ISSUE TITLE
Can't merge cells

### ISSUE THREAD

**Issue by denrique88** [miyako/4d-plugin-xls-basic-excel#2]
Hello,

As I was searching how to merge cells with the plugin, I figured it was possible to merge 2 columns and 2 rows ore more, but it's not possible to merge 2 rows in 1 column, nor 2 columns in 1 row.

I can see where the problem is in the code :
```
if(   (c > 0)
					 && (c <= ws->GetTotalCols())
					 && (r > 0)
					 && (r <= ws->GetTotalRows())
					 && (h > 1)
					 && ((h + r) <= ws->GetTotalRows())
					 && (w > 1)
&& ((w + c) <= ws->GetTotalCols())){
```

Do you think we can fix this ?

**Comment by miyako** [comment]
my memory is rusty re;this library, do you have any suggestions what should be done for this portion of code?

**Comment by denrique88** [comment]
Sorry, I wasn't notified of your answer.
I would do something like this :

```
if(   (c > 0)
					 && (c <= ws->GetTotalCols())
					 && (r > 0)
					 && (r <= ws->GetTotalRows())
					 && ((h > 1) || (w>1))
					 && ((h + r) <= ws->GetTotalRows())
&& ((w + c) <= ws->GetTotalCols())){
```

It means that the height or the width have to be > 1.

Which tool should I use to compile the plugin ?

**Comment by miyako** [comment]
I've integrated your code (not tested, I don't use the plugin) hope it works for you.

as a bonus, it is now thread safe (v17)

**Comment by denrique88** [comment]
That's an excellent news, thank you ! 
I'll test it as soon as I can.
