### ISSUE TITLE
Use in a merged client/server applications

### ISSUE THREAD

**Issue by pol-itworx** [miyako/4d-plugin-xls-basic-excel#3]
Hello,

First, thanx a lot for your great work.

The plugin works fine in an interpreted, compiled environnement, even in a client/server mode, but when the server and the client are engined we've got an privilege error that I may understand but this is not that far from a compiled application or C/S application.
I builded a C/S app just with the plugin, it works too.
Sorry for the screen captures in french, this says that there is a privilege error, I know that if you use a 32 bits plugin this appears, but why now ?
I've got the last version you provided (M1), my application works on Windows and Mac, the server is always on a PC server running MS 2019.
![error_mac](https://user-images.githubusercontent.com/40853904/114041255-ab2ead00-9884-11eb-819e-7a1a2a44c9da.png)
![error_win](https://user-images.githubusercontent.com/40853904/114041281-b1bd2480-9884-11eb-8e4a-80a29daf348b.png)

I'm on 4D v18R5, and burning a fuse... I don't understand what happens.

Merci, Pascal OLRY.

**Comment by miyako** [comment]
the version code (1.0) is suspicious, are you sure you don't have an older version cached by the server (.4darchive) or the client (cache)?

**Comment by miyako** [comment]
there is a bug in 18 R5 where a plugin replaced on the server side does not trigger an update on the client side ACI0101807

**Comment by pol-itworx** [comment]
It seems to work now:
I removed all .4Darchive, plus I renamed the plugins (XLS and XLS II), then I recompiled and generated the engined server and clients.
This worked, thank you!!!!!!!!!
