### ISSUE TITLE
Is this plugin compatible with 4Dv20?

### ISSUE THREAD

**Issue by ghirance** [miyako/4d-plugin-xls-basic-excel#4]
Currently, we are using XLS II in 4Dv16.4, and we are going to upgrade to 4Dv20. We have many reports that use the XLS plugin, and we would like to know if this is still working on 4Dv20.

**Comment by miyako** [comment]
Mac or Windows?

**Comment by ghirance** [comment]
Windows

**Comment by miyako** [comment]
the plugin is just a standard windows DLL, I haven't tested but I think you should try.

**Comment by ghirance** [comment]
would you recommend us to migrate our reports using with 4d write pro in the future?

**Comment by miyako** [comment]
I do not have an opinion. it is your decision.
